spring:
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/annonce_api
    username: postgres
    password: root

server:
  port: 8082

logging:
  file:
    name: logs/all-logs.log
  level:
    root: info
    com.example.annonceapi : debug

#springdoc:
#  api-docs:
#    path: /v1/docs
#  swagger-ui:
#    path: /swagger.html
#    try-it-out-enabled: true
#    display-request-duration: true
#    doc-expansion: true